### PR TITLE
Updates to all cosmos db CLI script samples

### PR DESCRIPTION
**Pull request by markjbrown**
Updating all of the Cosmos DB CLI sample scripts.

@SnehaGunda, please review and merge if no issues.

### CODE REVIEW

**Comment by markjbrown** [comment]
please hold on merging this. More changes coming. thanks.

**Comment by markjbrown** [comment]
@SnehaGunda ok, ready for review.

thanks.

**Comment by SnehaGunda** [comment]
@markjbrown Thank you, the changes look good.

**Comment by SnehaGunda** [comment]
#sign-off

**Comment by SnehaGunda** [comment]
@erickson-doug can you please merge this PR.

**Pull request merged**
