### PR TITLE
ACR: Updated assign-role script

### PR DESCRIPTION
**Pull request by dlepow**

### CODE REVIEW

**Comment by dlepow** [comment]
Fixes https://github.com/MicrosoftDocs/azure-docs/issues/25656

**Comment by dlepow** [comment]
@erickson-doug - Doug, can you please review/merge this PR when you have a chance? Thanks!

**Comment by erickson-doug** [comment]
adding @Stephen Tramer<mailto:Stephen.Tramer@microsoft.com>

--
Doug Erickson (douge) -- 425 273 1304

________________________________

**Comment by dlepow** [comment]
@sptramer - FYI, this PR covers a similar scenario to this one in the PoweShell samples repo: https://github.com/Azure/azure-docs-powershell-samples/pull/172

**Pull request merged**
