### PR TITLE
Add Python mount share example

### PR DESCRIPTION
**Pull request by ggailey777**
## Description

Add a new Linux consumption file share mount example

## Checklist

- [X] Scripts in this pull request are written for the `bash` shell.
- [ ] This pull request was tested on __at least one of__ the following platforms:
  - [ ] Linux
  - [X] Azure Cloud Shell
  - [ ] macOS
  - [ ] Windows Subsystem for Linux
- [X] Scripts do not contain passwords or other secret tokens.
- [X] No deprecated commands or arguments are used. ([Release notes](https://docs.microsoft.com/cli/azure/release-notes-azure-cli))
- [X] All Azure resource identifiers which must be universally unique are guaranteed to be so.

### Testing information

CLI version:
```
latest cloud shell
```

Extensions required:

### CODE REVIEW

**Comment by ggailey777** [comment]
#sign-off

**Comment by ggailey777** [comment]
@sdwheeler are you still the person who handles these? Thanks!

**Comment by sdwheeler** [comment]
@dbradish-microsoft owns the Azure CLI content.

**Comment by dbradish-microsoft** [comment]
#sign-off

**Comment by dbradish-microsoft** [comment]
@ggailey777 , as an FYI, I am not an Admin on this repo so I cannot merge your PR.  I also spoke with @Barbkess and confirmed that there is no requirement for me to validate all the Azure CLI being written cross-services.  (This would make me a major roadblock as there are hundreds of articles and multiple updates to Azure CLI articles daily.)  I am strongly focused on best practices, helping to improve Acrolinx for Azure CLI business rules, working with Aquent for testing and cross-service updates, and writing articles for the azure-docs-cli repo.  I also try and keep my finger on the pulse of reported new and outstanding issues (i.e. Azure CLI help desk).  All said, I entered a sign-off comment above, and will speak to the Azure CLI technical team for a SOP for samples moving forward.

**Comment by craigshoemaker** [comment]
@ggailey777 - why are you hard-coding this demo to the West Europe region?

**Comment by ggailey777** [comment]
@craigshoemaker no reason...that's how we did the rest of them (or once we had to avoid using US West). Should I make it into a variable?

**Comment by ggailey777** [comment]
@craigshoemaker I addressed your suggestion to parameterize the region across the other example scripts. I also added the `--functions-version` to the other scripts to suppress a new warning.

**Comment by ggailey777** [comment]
@sdwheeler several folks have now reviewed this PR, and @kulkarnisonia16 has approved, so we can consider this a #sign-off. Please merge this when you get a chance. Thanks!

**Comment by ggailey777** [comment]
@sdwheeler Thanks!

**Pull request merged**
