### PR TITLE
fxl---Fixed typos in script

### PR DESCRIPTION
**Pull request by flang-msft**
## Checklist

- [x] Scripts in this pull request are written for the `bash` shell.
- [x] This pull request was tested on __at least one of__ the following platforms:
  - [ ] Linux
  - [x] Azure Cloud Shell
  - [ ] macOS
  - [ ] Windows Subsystem for Linux
- [x] The most recent test date and test method are recorded in the script file.
- [x] Scripts do not contain passwords or other secret tokens that are not randomized.
- [x] No deprecated commands or arguments are used. ([Release notes](https://docs.microsoft.com/cli/azure/release-notes-azure-cli))
- [x] All Azure resource identifiers which must be universally unique are guaranteed to be so.
- [x] Resource names use a random function to ensure scripts can be run multiple times in quick succession without error.
- [x] All scripts can be run in their entirely without user input.

### Testing information

CLI version:
```
az --version
```

Extensions required:

### CODE REVIEW

**Comment by flang-msft** [comment]
#sign-off

**Comment by flang-msft** [comment]
#sign-off

**Review by shpathak-msft — APPROVED** [review]

**Comment by flang-msft** [comment]
@shpathak-msft - thank you for the approval. What happens next to get them to merge?

**Comment by flang-msft** [comment]
@dbradish-microsoft @mikefrobbins - I don't know how to get this merged but you merged previous submissions. I'm trying to fix a github issue on my content that "include" a file here that I've corrected. Can you let me know how to get this merged, please?

**Comment by flang-msft** [comment]
@dbradish-microsoft - Thanks for the merge. Do you know if/when the "master" branch would be renamed "main"?

**Pull request merged**
